name: registratrix_flutter
description: Create and register for groups and events at your organisation.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  backstreets_widgets: ^0.16.0
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  form_builder_validators: ^11.0.0
  registratrix_client:
    path: ../registratrix_client
  serverpod_auth_email_flutter: 2.1.1
  serverpod_auth_shared_flutter: 2.1.1
  serverpod_flutter: 2.1.1

dev_dependencies:
  flutter_lints: ">=3.0.0 <5.0.0"
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
