name: registratrix_server
description: The Registratrix server.
environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  mailer: ^6.1.2
  serverpod: 2.1.1
  serverpod_auth_server: 2.1.1

dev_dependencies:
  lints: '>=3.0.0 <5.0.0'
